POST http://localhost:5000/createurl
Accept: application/json
Content-Type: application/json

{
    "full_url": "https://www.google.com"
}

###

GET http://localhost:5000/geturl

###
POST http://localhost:5000/signup
content-Type: application/json

{
    "email": "email@email.com",
    "password": "password12"
}